### ISSUE TITLE
Crashing when deploying Windows

### ISSUE THREAD

**Issue by TheMorc** [BigfootACA/linux-simple-mass-storage#2]
👋 Hi! 
![P1080847](https://user-images.githubusercontent.com/13377926/210289303-b6afd027-7067-47e3-9eda-2e781675539f.JPG)

I seem to hit a weird issue where when deploying Windows, it suddenly stops copying files (my VM that I use for deploying sees this as 100% Active time in task manager) and if it doesn't unfreeze after two minutes it kernel panics on a hung task.

I still haven't checked with a different PC if it is some sort of an incompatibility between my MacBook, USB controller and the Parallels arm64 VM but I thought it would be good to submit an issue just in case.

**Comment by TheMorc** [comment]
UPDATE: The issue is in fact somewhere between my MacBook, the USB controller and the VM.
I tried using a different PC directly with USB-C ports and the deploy process was quicker and also finished just fine.

**Comment by BigfootACA** [comment]
what host os version are you having issues with? sophon has a compatibility issue with the uaspstor driver on windows 11, im not sure if you have the same issue.

**Comment by TheMorc** [comment]
> what host os version are you having issues with? sophon has a compatibility issue with the uaspstor driver on windows 11, im not sure if you have the same issue.

I have an old Windows 11 build, still 22000
<img width="194" alt="image" src="https://user-images.githubusercontent.com/13377926/210872034-32c33ee0-c67b-4eb1-90b3-b19d17d3bcd6.png">

**Comment by TheMorc** [comment]
Also one thing I noticed, the issue seems to be quite a bit more related to dism operations (or maybe things where you need to copy a lot of random data compared to sequential data) than anything else because I was able to copy a 20GB file without any problems.

**Comment by BigfootACA** [comment]
sophon said that on windows 11, the host driver will send the TASK_MANAGEMENT command, but the f_tcm in the linux kernel does not handle this command correctly, which eventually leads to a crash. you may have to ask sophon for details
